# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy: 
        matrix:
          java: [ 1.8, 11, 15 ]
        fail-fast: false
    name: Java ${{ matrix.java }} sample
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -B verify --file pom.xml && ls ~/.m2/repository/ && ls ~/.m2/repository/de/dagere/kopeme/kopeme-core
    - name: Publish Test Report ${{ matrix.java }}
      if: ${{ always() }}
      uses: scacap/action-surefire-report@v1
      with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload Unit Test Results
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: Unit Test Results (Java ${{ matrix.java }})
        path: target/surefire-reports/*
  publish-test-results:
    name: "Publish Unit Tests Results"
    needs: build
    runs-on: ubuntu-latest
    if: success() || failure()
    steps:
    - name: Download Artifacts
      uses: actions/download-artifact@v2
      with:
        path: artifacts
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        check_name: Unit Test Results
        files: target/surefire-reports/.xml
